### ISSUE TITLE
ocaml and yocto

### ISSUE THREAD

**Issue by liambeguin** [whirm/ocaml-arm#1]
Hi, 

I don't know if this is the right place but I came across your post on IRC #yocto. 
https://www.yoctoproject.org/irc/%23yocto.2015-06-07.log.html
I was wondering, did you manage to finish your recipe ?
I'm trying to do the same thing using a custom toolchain.  
Regards,

Liam

**Comment by whirm** [comment]
I'm not using this repo anymore, but AFAIR it worked.

**Comment by liambeguin** [comment]
ok, Thanks

**Comment by whirm** [comment]
NP, good luck!
